#cloud-config
users:
  - name: yc-user
    groups: sudo
    shell: /bin/bash   #!/usr/bin/env bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDDMqexxqBDzloOivYbSNZKXsXGJLHt+DWCZx6JMjLZ2pJghuaB5Q8Lpy1jwbqZYPw67k+OqjWnhjcY5vwWdj9aB5vVrKBrAMe7/11ekm7+vUXXi0r893FKqTYpHSWOgxxVlMEcVkZJyWR26ZaRbm3qxChT/uwDQGT2QsXehkzZeN3U9HN2tBEPj4FpZiLAY29ix259JUaltDZj2cprKtde0q4zfWFwQQo3/vyRyCA2iZov74ZWdSjmjCPLEPYMlm7kfgduxawxQ+kkVZvsvvORbh7shUmxbbdH8ey045Blox2rn9jllDc8BNCbnNgnboDj7Wyg/b4gmtFwE+L73txhEL5mMfEicJvExiyIfCWOmh0nV6vzJEjdXyOJ7QqGn0zNlwIzRFSwiZ/dnXPDHqHXz4J4N3BA+j+I0VM6NFe+J1jTyL4NxYZ651lmZPV6yZjeME4xfdSZdYQfZMyaf/f+5MDmReymo7f1IuhkD/+4zkdHmm3BFV8sBvvHd1CJDwVYPpSURgRtx/PXHaPURL9tgxw1zh1Lbg3QnW7ghB2zg5l10ZQDwttP4eSTs0AwqFmCacC177lTvbu7oGonReqBorU5LqZr7ai65QhMGfi5W13JMwonvv1a4+Nvztr353HOya1uikzE+5APQFlBLayX0TAhtchB7uv1wXyGyb/wEw== appuser

package_update: true

write_files:
  - path: /home/yc-user/startup_script.sh
    owner: yc-user:yc-user
    permissions: '0755'
    content: |
      sudo apt install git apt-transport-https ca-certificates -y
      sudo apt install gnupg
      sudo apt update -y
      sudo apt upgrade -y
      wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
      echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
      sudo apt update -y
      sudo apt install -y mongodb-org
      sudo systemctl daemon-reload
      sudo systemctl enable mongod
      sudo systemctl start mongod
      sudo apt install -y ruby-full ruby-bundler build-essential
      sudo apt install git -y
      git clone -b monolith https://github.com/express42/reddit.git
      cd reddit && bundle install
      puma -d
runcmd:
    - bash /home/yc-user/startup_script.sh
